"""add recipient validation errors table

Revision ID: 06b7aa5a6788
Revises: 20fed4848552
Create Date: 2025-11-07 16:10:31.437284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06b7aa5a6788'
down_revision: Union[str, None] = '20fed4848552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipient_validation_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('batch_id', sa.BigInteger(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_phone', sa.String(length=32), nullable=True),
    sa.Column('raw_name', sa.String(length=100), nullable=True),
    sa.Column('reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['recipient_batches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_validation_batch_row', 'recipient_validation_errors', ['batch_id', 'row_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_validation_batch_row', table_name='recipient_validation_errors')
    op.drop_table('recipient_validation_errors')
    # ### end Alembic commands ###
