"""add phone hash to recipients

Revision ID: 20fed4848552
Revises: 143a4cef797a
Create Date: 2025-11-06 23:44:14.527194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20fed4848552'
down_revision: Union[str, None] = '143a4cef797a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaign_recipients', sa.Column('phone_hash', sa.LargeBinary(), nullable=False))
    op.drop_index('ix_recipient_phone_hash', table_name='campaign_recipients', mysql_length={'enc_phone': 3072})
    op.create_index('ix_recipient_phone_hash', 'campaign_recipients', ['phone_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_recipient_phone_hash', table_name='campaign_recipients')
    op.create_index('ix_recipient_phone_hash', 'campaign_recipients', ['enc_phone'], unique=False, mysql_length={'enc_phone': 3072})
    op.drop_column('campaign_recipients', 'phone_hash')
    # ### end Alembic commands ###
